# Generated by Django 5.0.6 on 2024-06-26 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='default_value', max_length=200, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=200, verbose_name='Apellido')),
                ('dni', models.IntegerField(null=True, unique=True, verbose_name='DNI')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('cuit', models.IntegerField(null=True, unique=True, verbose_name='CUIT')),
                ('turno', models.CharField(max_length=100, verbose_name='Turno')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('especie', models.CharField(max_length=100, verbose_name='Especie')),
                ('tamaño', models.CharField(max_length=100, verbose_name='Tamaño')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('manto', models.CharField(max_length=100, verbose_name='Manto')),
                ('castracion', models.CharField(max_length=10, verbose_name='Castracion')),
            ],
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='default_value', max_length=200, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=200, verbose_name='Apellido')),
                ('dni', models.IntegerField(null=True, unique=True, verbose_name='DNI')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('localidad', models.CharField(max_length=100, verbose_name='Localidad')),
                ('vivienda', models.CharField(max_length=100, verbose_name='Vivienda')),
                ('tieneMascota', models.CharField(max_length=10, verbose_name='Tiene Mascota')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo')),
                ('mascota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.mascota')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entevista', models.DateField(verbose_name='Fecha de Entrevista')),
                ('adopcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.mascota')),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.postulante')),
            ],
        ),
        migrations.CreateModel(
            name='Refugio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala1', models.CharField(max_length=100, verbose_name='Sala 1')),
                ('sala2', models.CharField(max_length=100, verbose_name='Sala 2')),
                ('sala3', models.CharField(max_length=100, verbose_name='Sala 3')),
                ('sala4', models.CharField(max_length=100, verbose_name='Sala 4')),
                ('mascotas', models.ManyToManyField(to='web.mascota')),
            ],
        ),
    ]
